Categories = {
			  [0] = GetLabelText('VEH_CLASS_0'),	--Compacts
			  [1] = GetLabelText('VEH_CLASS_1'),	--Sedans
			  [2] = GetLabelText('VEH_CLASS_2'),	--SUVs
			  [3] = GetLabelText('VEH_CLASS_3'),	--Coupes
			  [4] = GetLabelText('VEH_CLASS_4'),	--Muscle
			  [5] = GetLabelText('VEH_CLASS_5'),	--Sports Classics
			  [6] = GetLabelText('VEH_CLASS_6'),	--Sports
			  [7] = GetLabelText('VEH_CLASS_7'),	--Super
			  [8] = GetLabelText('VEH_CLASS_8'),	--Motorcycles
			  [9] = GetLabelText('VEH_CLASS_9'),	--Off-road
			  [10] = GetLabelText('VEH_CLASS_10'),	--Industrial
			  [11] = GetLabelText('VEH_CLASS_11'),	--Utility
			  [12] = GetLabelText('VEH_CLASS_12'),	--Vans
			  [13] = GetLabelText('VEH_CLASS_13'),	--Cycles
			  [14] = GetLabelText('VEH_CLASS_14'),	--Boats
			  [15] = GetLabelText('VEH_CLASS_15'),	--Helicopters
			  [16] = GetLabelText('VEH_CLASS_16'),	--Planes
			  [17] = GetLabelText('VEH_CLASS_17'),	--Service
			  [18] = GetLabelText('VEH_CLASS_18'),	--Emergency
			  [19] = GetLabelText('VEH_CLASS_19'),	--Military
			  [20] = GetLabelText('VEH_CLASS_20'),	--Commercial
			  [21] = GetLabelText('VEH_CLASS_21'),	--Trains
			  [22] = GetLabelText('TRAILER'), 		--Trailers
			  [23] = 'Alfa romeo',
			  [24] = 'Apollo',
			  [25] = 'Audi',
			  [26] = 'Austin Martin',
			  [27] = 'Bentley',
			  [28] = 'BMW',
			  [29] = 'Brabus',
			  [30] = 'Buick',
			  [31] = 'Cadillac',
			  [32] = 'Cheverolet',
			  [33] = 'Chrysler',
			  [34] = 'Devel Sixteen',
			  [35] = 'Dodge',
			  [36] = 'Ferrari',
			  [37] = 'Ford',
			  [38] = 'Geely',
			  [39] = 'Genesis',
			  [40] = 'GMC',
			  [41] = 'Haval',
			  [42] = 'Hennessey',
			  [43] = 'Holden',
			  [44] = 'Honda',
			  [45] = 'Hyundai',
			  [46] = 'Infiniti',
			  [47] = 'Jaguar',
			  [48] = 'Jeep',
			  [49] = 'Kia',
			  [50] = 'Koenigsegg',
			  [51] = 'Lada',
			  [52] = 'Lamborghini',
			  [53] = 'Land Rover',
			  [54] = 'Lexus',
			  [55] = 'Lincoln',
			  [56] = 'Maserati',
			  [57] = 'Mazda',
			  [58] = 'McLaren',
			  [59] = 'Mercedes',
			  [60] = 'Mini',
			  [61] = 'Nissan',
			  [62] = 'Porsche',
			  [63] = 'Rolls Royce',
			  [64] = 'Tesla',
			  [65] = 'Toyota',
			  [66] = 'Volkswagen',
			  [67] = 'Trucks',
			  [68] = 'Classic',
			  [69] = 'Other',
			  [70] = 'Hummer',
			  [71] = 'Plane',
			  [72] = '',
			  [73] = '',
			  [74] = '',
			  [75] = '',
			  [76] = '',
			  [77] = '',
			  [78] = '',
			  [79] = '',
			  [80] = '',
			  [81] = '',
			  [82] = '',
			  [83] = '',
			  [84] = '',
			  [85] = '',
			  [86] = '',
			  [87] = '',
			  [88] = '',
			  [89] = '',
			  [90] = '',
			  [91] = '',
			  [92] = '',
			  [93] = '',
			  
			 }

